### ISSUE TITLE
type: schemas no longer satisfy standard-schema at the type level (ai SDK interop)

### ISSUE THREAD

**Issue by denny-il** [neematajs/neemata#228]
## Problem

`@nmtjs/type` schemas implement standard-schema at runtime (`'~standard' in schema` is true), but the 0.17 type declarations no longer expose it. Anything generic over `StandardSchemaV1` fails to infer.

Concrete case: the Vercel AI SDK's structured output, which worked with t schemas on 0.16:

```ts
const { output } = await generateText({
  ...,
  output: Output.object({ schema: IdentitySchema }),  // t.object(...)
})
// 0.16: output typed from the schema
// 0.17: schema no longer matches FlexibleSchema<T> -> OUTPUT generic collapses,
//       result degrades and property access errors:
//       "Property 'name' does not exist on type 'string'"
```

Workaround in every affected call site:

```ts
output: Output.object<t.infer.decode.output<typeof IdentitySchema>>({
  schema: IdentitySchema as never,
}),
```

Since the runtime contract is already there, restoring the `'~standard'` property on the declared `BaseType` (typed per StandardSchemaV1 with the schema's decode types) would fix AI SDK and any other standard-schema consumer without runtime changes.

`@nmtjs/type@0.17.0-beta.1` with `ai@6.x`.

**Comment by denny-il** [comment]
Fixed and released in v0.17.0-beta.2: https://github.com/neematajs/neemata/releases/tag/v0.17.0-beta.2\n\nRegression coverage landed in #234 for StandardSchemaV1 generic output inference, covering the AI SDK interop path. Please reopen if this still reproduces on beta.2.
